# basic
title: 老孟
subtitle: Minimalism, simplicity and refined details
favicon: https://hexo.io/icon/favicon-96x96.png

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
logo: ./img/lm.png

# disqus
#disqus_shortname: drakeleung

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# nav #
nav:
  home: .
  archive: archives
  # about: about
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/vickmeng
  # weibo: http://weibo.com/10010800
  # mail: mailto:gallenhu@foxmail.com
  # twitter: https://twitter.com/GallenHu

# widget
#   title: 标题
#   content: 内容
widget:
  title: 相关
  content: <ul><li><a href="https://github.com/RxJS-CN">RxJS 中文社区</a></li><li><a href="https://github.com/vickmeng/ng-vk-charts">数据可视化ng-vk-charts</a></li></ul>

footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> with Theme <a href="https://github.com/GallenHu/hexo-theme-Daily" target="_blank">Daily</a>
